### ISSUE TITLE
Test project needs secret clean up

### ISSUE THREAD

**Issue by averikitsch** [googleapis/python-secret-manager#55] opened 2020-11-10 19:31 UTC
The test project has +2000 secrets due to testing that need to be cleaned up. Tests should be reviewed for proper clean up.

**Comment by tam7t** [comment] 2021-02-08 15:45
https://cloud.google.com/secret-manager/docs/creating-and-managing-expiring-secrets adds a feature to set a [TTL](https://google.aip.dev/214) on the `Secret` resource which schedules the secret for deletion.

Another alternative is a test case that just lists and deletes secrets older a predefined duration.

**Comment by parthea** [comment] 2023-04-15 13:53
Closing as duplicate of https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9643

**Closed by parthea** 2023-04-15 13:53 UTC
Labels: api: secretmanager, type: cleanup, priority: p2
