### ISSUE TITLE
API call stuck forever in python 2.7 when used with import

### ISSUE THREAD

**Issue by tarunbhardwaj** [googleapis/python-secret-manager#39] opened 2020-08-20 14:39 UTC
#### Environment details

  - OS type and version:  Ubuntu 16.04
  - Python version: Python 2.7.18 (works fine in Python 3.x)
  - pip version: 20.2.2
  - `google-cloud-secret-manager` version: 1.0.0

#### Steps to reproduce

  1. Create file which access secrets

     ```python
     # test.py
     import logging
     from google.cloud import secretmanager
     
     logging.basicConfig(level=logging.DEBUG)
     
     client = secretmanager.SecretManagerServiceClient()
     secret_path = client.secret_version_path('xxx', 'xxx', 'xxx')
     print('Loading Secrets')
     response = client.access_secret_version(secret_path, timeout=5)
     print('Done')
     ```

  2. Run

     ```bash
     python test.py
     ```

     All Good:

     ```
     DEBUG:google.auth._default:Checking None for explicit credentials as part of auth process...
     DEBUG:google.auth._default:Checking Cloud SDK credentials as part of auth process...
     Loading Secrets
     DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
     DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
     DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
     Done
     ```

  3. Run 

     ```bash
     python -c "import test"
     ```

     Stuck forever:

     ```
     DEBUG:google.auth._default:Checking None for explicit credentials as part of auth process...
     DEBUG:google.auth._default:Checking Cloud SDK credentials as part of auth process...
     Loading Secrets
     DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
     DEBUG:google.api_core.retry:Retrying due to 503 Deadline Exceeded, sleeping 0.0s ...
     DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
     DEBUG:google.api_core.retry:Retrying due to 503 Deadline Exceeded, sleeping 0.1s ...
     DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
     DEBUG:google.api_core.retry:Retrying due to 503 Deadline Exceeded, sleeping 0.1s ...
     ...
     ```

     

#### Code example

```python
import logging
from google.cloud import secretmanager

logging.basicConfig(level=logging.DEBUG)

client = secretmanager.SecretManagerServiceClient()
secret_path = client.secret_version_path('xxx', 'xxx', 'xxx')
print('Loading Secrets')
response = client.access_secret_version(secret_path, timeout=5)
print('Done')
```

#### Stack trace

```
DEBUG:google.auth._default:Checking None for explicit credentials as part of auth process...
DEBUG:google.auth._default:Checking Cloud SDK credentials as part of auth process...
Loading Secrets
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:google.api_core.retry:Retrying due to 503 Deadline Exceeded, sleeping 0.0s ...
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:google.api_core.retry:Retrying due to 503 Deadline Exceeded, sleeping 0.1s ...
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:google.api_core.retry:Retrying due to 503 Deadline Exceeded, sleeping 0.1s ...
...
```

**Comment by busunkim96** [comment] 2020-08-20 16:20
Hi @tarunbhardwaj, I'm not able to reproduce this using 2.7.18 and the code provided.

Is there anything else different about the 2.7 and 3 environments you're using? What kind of credentials are you using?

**Comment by haimjether** [comment] 2021-07-27 10:47
Confirming same issue (API call stuck) at 
OS: Ubuntu 20.04
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
conda 4.8.3

```
google-api-core==1.31.0
google-api-python-client==2.14.0
google-auth==1.33.1
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.4
google-cloud-core==1.7.1
google-cloud-secret-manager==2.6.0
google-crc32c==1.1.2
google-resumable-media==1.3.1
googleapis-common-protos==1.53.0
grpc-google-iam-v1==0.12.3
pydata-google-auth==1.2.0
```

Tried adding `timeout` to `secretmanager.SecretManagerServiceClient().access_secret_version(name='xxx', timeout=10)`
```
DEBUG:google.auth._default:Checking None for explicit credentials as part of auth process...
DEBUG:google.auth._default:Checking Cloud SDK credentials as part of auth process...
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
```

**Comment by busunkim96** [comment] 2021-07-27 15:07
Hey @haimjether,

A few questions to try to figure out what's happening:

- Are you able to make any other calls to Google Cloud APIs successfully? 
- What environment is the code being run in? Are there any proxies or firewalls at play?

**Comment by haimjether** [comment] 2021-07-27 15:13
Hey @busunkim96 ,
thanks for the brief response. 

1. yes I am able to make calls to Google Cloud API , even with the secret manager - but not with nosetests (I suspect it's related to it , since switching to pytest seems to work fine)
2. This is my local Ubuntu 20.04 box, no proxies, no firewalls at all.

**Comment by parthea** [comment] 2022-02-26 18:36
I'm going to close this issue as obsolete but please feel free to re-open it.

**Closed by parthea** 2022-02-26 18:36 UTC
Labels: api: secretmanager, type: question

**Comment by aseem-heg** [comment] 2022-08-27 04:09
Got this error when using secret manager in python. 
Same code ran successfully after 3 minutes. Perhaps some bug on gcp side. 

![Screenshot from 2022-08-26 23-06-23](https://user-images.githubusercontent.com/86262107/187013753-8796188b-f3ed-4d2b-b79b-34df9aa63eb6.png)
